<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibTeX" nsURI="bibtex" nsPrefix="bibtex">
  <eAnnotations source="Diagram">
    <details key="name" value="BibTeX"/>
    <details key="icon" value="icons/application-diagram-16.png"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BibTeXFile">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//BibTeXEntry" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibTeXEntry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthoredEntry" abstract="true" eSuperTypes="#//BibTeXEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" lowerBound="1"
        upperBound="-1" eType="#//Author" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatedEntry" abstract="true" eSuperTypes="#//BibTeXEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TitledEntry" abstract="true" eSuperTypes="#//BibTeXEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookTitledEntry" abstract="true" eSuperTypes="#//BibTeXEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="#//AuthoredEntry #//DatedEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechReport" eSuperTypes="#//AuthoredEntry #//DatedEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unpublished" eSuperTypes="#//AuthoredEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manual" eSuperTypes="#//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proceedings" eSuperTypes="#//DatedEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InProceedings" eSuperTypes="#//Proceedings #//AuthoredEntry #//BookTitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Booklet" eSuperTypes="#//DatedEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//AuthoredEntry #//DatedEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InCollection" eSuperTypes="#//Book #//BookTitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InBook" eSuperTypes="#//Book">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Misc" eSuperTypes="#//BibTeXEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThesisEntry" abstract="true" eSuperTypes="#//AuthoredEntry #//DatedEntry #//TitledEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="school" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhDThesis" eSuperTypes="#//ThesisEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterThesis" eSuperTypes="#//ThesisEntry">
    <eAnnotations source="Node">
      <details key="base" value="Artifact"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
