<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chess" nsURI="Chess" nsPrefix="Chess">
  <eClassifiers xsi:type="ecore:EClass" name="ChessGame">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rounds" upperBound="-1"
        eType="#//Round" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Piece">
    <eLiterals name="KING"/>
    <eLiterals name="ROOK" value="1"/>
    <eLiterals name="QUEEN" value="2"/>
    <eLiterals name="PAWN" value="3"/>
    <eLiterals name="KNIGHT" value="4"/>
    <eLiterals name="BISHOP" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Player">
    <eLiterals name="WHITE"/>
    <eLiterals name="BLACK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonEmptySquare" eSuperTypes="#//Square">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="piece" eType="#//Piece"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="player" eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveType" lowerBound="1"
        eType="#//MoveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="piece" eType="#//Piece"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptySquare" eSuperTypes="#//Square"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MoveType">
    <eLiterals name="MOVE"/>
    <eLiterals name="CAPTURE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Round">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moves" upperBound="2" eType="#//Move"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Event">
    <eLiterals name="CHESS"/>
    <eLiterals name="CHESSMATE" value="1"/>
    <eLiterals name="CHECK" value="2"/>
  </eClassifiers>
</ecore:EPackage>
