<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cobol" nsURI="cobol" nsPrefix="cobol">
  <eAnnotations source="Diagram">
    <details key="label" value="COBOL"/>
    <details key="icon" value="icons/application-diagram-16.png"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CBLElements" upperBound="-1"
        eType="#//COBOLElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CBLClassifiers" upperBound="-1"
        eType="#//COBOLClassifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CBLInitialValue" upperBound="-1"
        eType="#//COBOLElementInitialValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CBLSourceText" upperBound="-1"
        eType="#//COBOLSourceText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CBLElementValues" upperBound="-1"
        eType="#//COBOL88ElementValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedType" lowerBound="1"
        eType="#//COBOLClassifier">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" upperBound="-1"
        eType="#//COBOLComposedType">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" upperBound="-1"
        eType="#//COBOLElementInitialValue">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//COBOL88Element" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//COBOLSourceText">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" upperBound="-1"
        eType="#//COBOLFixedLengthArray" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLClassifier">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedElements" upperBound="-1"
        eType="#//COBOLElement">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLSimpleType" eSuperTypes="#//COBOLClassifier">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pictureString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLComposedType" eSuperTypes="#//COBOLClassifier">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//COBOLElement" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLElementInitialValue">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initVal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOL88Element">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" lowerBound="1" upperBound="-1"
        eType="#//COBOL88ElementValue" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOL88ElementValue">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLRedefiningElement" eSuperTypes="#//COBOLElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefines" lowerBound="1"
        eType="#//COBOLElement">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOL66Element">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//COBOLElement">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//COBOLElement">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLSourceText">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLFixedLengthArray">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxUpper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COBOLVariableLengthArray" eSuperTypes="#//COBOLFixedLengthArray">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minUpper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependingOn" lowerBound="1"
        eType="#//COBOLElement">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
