<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conference" nsURI="conference" nsPrefix="conference">
  <eAnnotations source="Diagram">
    <details key="name" value="Conference"/>
    <details key="icon" value="icons/application-diagram-16.png"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferences" upperBound="-1"
        eType="#//Conference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conference">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ConferenceElement" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" lowerBound="1"
        upperBound="-1" eType="#//Participant">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="speakers" lowerBound="1"
        upperBound="-1" eType="#//Participant" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Track" eSuperTypes="#//ConferenceElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//Slot" containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot" eSuperTypes="#//TimedElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="talk" lowerBound="1" eType="#//Talk"
        containment="true">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Talk" eSuperTypes="#//Conference">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenter" lowerBound="1"
        eType="#//Participant">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/association-16.png"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eAnnotations source="Node">
      <details key="base" value="Actor"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lunch" eSuperTypes="#//ConferenceElement #//TimedElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedElement">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/ApplicationComponent.svg"/>
      <details key="icon" value="icons/application-component-16.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
