<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Process" nsURI="sdpl" nsPrefix="sdpl">
  <eAnnotations source="Diagram">
    <details key="name" value="SDPL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Step">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/step.svg"/>
      <details key="icon" value="icons/step.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" lowerBound="1" eType="#//Step"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/tool.svg"/>
      <details key="icon" value="icons/tool.png"/>
      <details key="bold" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="Node">
      <details key="base" value="Class"/>
      <details key="shape" value="shapes/per.svg"/>
      <details key="icon" value="icons/per.png"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familiarWith" upperBound="-1"
        eType="#//Tool">
      <eAnnotations source="Edge">
        <details key="base" value="Association"/>
        <details key="icon" value="icons/line.png"/>
        <details key="fontHeight" value="15"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eAnnotations source="Edge">
      <details key="base" value="Association"/>
      <details key="icon" value="icons/line.png"/>
      <details key="source" value="src"/>
      <details key="target" value="tar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Step"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tar" lowerBound="1" eType="#//Person"/>
  </eClassifiers>
</ecore:EPackage>
